%% ATFIDP - OpenRocket -> Simulink Integration Model

clear;
clc;

%% Project paths

project_root = fileparts(fileparts(mfilename('fullpath')));
model_dir = fullfile(project_root, 'models');

if ~exist(model_dir, 'dir')
    mkdir(model_dir);
end

model_name = 'ATFIDP_OpenRocket_Integration';
model_path = fullfile(model_dir, [model_name '.slx']);

%% Close/delete existing model

if bdIsLoaded(model_name)
    close_system(model_name, 0);
end

if exist(model_path, 'file')
    delete(model_path);
end

%% Load prepared OpenRocket data

data_file = fullfile( ...
    project_root, ...
    'data', ...
    'openrocket_simulink_data.mat');

load(data_file);

fprintf('ATFIDP OpenRocket -> Simulink Integration\n');
fprintf('-----------------------------------------\n');

%% Create model

new_system(model_name);
open_system(model_name);

%% Simulation settings

set_param(model_name, ...
    'StartTime', '0.01', ...
    'StopTime', '1.98', ...
    'SolverType', 'Variable-step', ...
    'Solver', 'ode45');

%% INPUTS

add_block('simulink/Sources/From Workspace', ...
    [model_name '/Altitude'], ...
    'VariableName', 'openrocket_altitude', ...
    'Position', [40 50 180 80]);

add_block('simulink/Sources/From Workspace', ...
    [model_name '/Velocity'], ...
    'VariableName', 'openrocket_velocity', ...
    'Position', [40 140 180 170]);

add_block('simulink/Sources/From Workspace', ...
    [model_name '/Vertical Velocity'], ...
    'VariableName', 'openrocket_vertical_velocity', ...
    'Position', [40 230 180 260]);

add_block('simulink/Sources/From Workspace', ...
    [model_name '/Acceleration'], ...
    'VariableName', 'openrocket_acceleration', ...
    'Position', [40 320 180 350]);

add_block('simulink/Sources/From Workspace', ...
    [model_name '/Mach'], ...
    'VariableName', 'openrocket_mach', ...
    'Position', [40 410 180 440]);

%% SCOPES

add_block('simulink/Sinks/Scope', ...
    [model_name '/Altitude Scope'], ...
    'Position', [300 40 440 90]);

add_block('simulink/Sinks/Scope', ...
    [model_name '/Velocity Scope'], ...
    'Position', [300 130 440 180]);

add_block('simulink/Sinks/Scope', ...
    [model_name '/Vertical Velocity Scope'], ...
    'Position', [300 220 440 270]);

add_block('simulink/Sinks/Scope', ...
    [model_name '/Acceleration Scope'], ...
    'Position', [300 310 440 360]);

add_block('simulink/Sinks/Scope', ...
    [model_name '/Mach Scope'], ...
    'Position', [300 400 440 450]);

%% SIGNAL CONNECTIONS

add_line(model_name, ...
    'Altitude/1', ...
    'Altitude Scope/1');

add_line(model_name, ...
    'Velocity/1', ...
    'Velocity Scope/1');

add_line(model_name, ...
    'Vertical Velocity/1', ...
    'Vertical Velocity Scope/1');

add_line(model_name, ...
    'Acceleration/1', ...
    'Acceleration Scope/1');

add_line(model_name, ...
    'Mach/1', ...
    'Mach Scope/1');

%% SAVE

save_system(model_name, model_path);

fprintf('\n');
fprintf('============================================\n');
fprintf('OpenRocket Simulink Model Generated\n');
fprintf('============================================\n');
fprintf('Model: %s\n', model_path);
fprintf('Time:  %.2f -> %.2f s\n', ...
    openrocket_altitude.Time(1), ...
    openrocket_altitude.Time(end));
fprintf('Signals: 5\n');
fprintf('============================================\n');