%% ATFIDP Flight Computer - Simulink Model Generator
% Generates the complete Simulink model automatically.

clear;
clc;

%% Project paths

project_root = fileparts(fileparts(mfilename('fullpath')));
model_dir = fullfile(project_root, 'models');

if ~exist(model_dir, 'dir')
    mkdir(model_dir);
end

model_name = 'ATFIDP_FlightComputer';
model_path = fullfile(model_dir, [model_name '.slx']);

%% Delete existing model

if bdIsLoaded(model_name)
    close_system(model_name, 0);
end

if exist(model_path, 'file')
    delete(model_path);
end

%% Create new model

new_system(model_name);
open_system(model_name);

%% Simulation settings

set_param(model_name, ...
    'StartTime', '0', ...
    'StopTime', '60', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.1');

%% ============================================================
%  INPUT BLOCKS
% =============================================================

add_block('simulink/Sources/From Workspace', ...
    [model_name '/Temperature Input'], ...
    'VariableName', 'temperature_input', ...
    'Position', [40 60 180 90]);

add_block('simulink/Sources/From Workspace', ...
    [model_name '/Altitude Input'], ...
    'VariableName', 'altitude_input', ...
    'Position', [40 180 180 210]);

add_block('simulink/Sources/From Workspace', ...
    [model_name '/Velocity Input'], ...
    'VariableName', 'velocity_input', ...
    'Position', [40 300 180 330]);

add_block('simulink/Sources/From Workspace', ...
    [model_name '/Battery Input'], ...
    'VariableName', 'battery_input', ...
    'Position', [40 420 180 450]);

%% ============================================================
%  DIRECT SIGNAL SCOPES
% =============================================================

add_block('simulink/Sinks/Scope', ...
    [model_name '/Temperature Scope'], ...
    'Position', [260 50 390 100]);

add_block('simulink/Sinks/Scope', ...
    [model_name '/Altitude Scope'], ...
    'Position', [260 170 390 220]);

add_block('simulink/Sinks/Scope', ...
    [model_name '/Velocity Scope'], ...
    'Position', [260 290 390 340]);

add_block('simulink/Sinks/Scope', ...
    [model_name '/Battery Scope'], ...
    'Position', [260 410 390 460]);

%% ============================================================
%  HEALTH MONITOR - COMPARATORS
% =============================================================

add_block('simulink/Logic and Bit Operations/Compare To Constant', ...
    [model_name '/High Temperature Check'], ...
    'const', '80', ...
    'relop', '>', ...
    'Position', [260 90 420 125]);

add_block('simulink/Logic and Bit Operations/Compare To Constant', ...
    [model_name '/Low Battery Check'], ...
    'const', '20', ...
    'relop', '<', ...
    'Position', [260 450 420 485]);

%% ============================================================
%  STATUS CONSTANTS
% =============================================================

add_block('simulink/Sources/Constant', ...
    [model_name '/Status Critical'], ...
    'Value', '2', ...
    'Position', [520 30 610 60]);

add_block('simulink/Sources/Constant', ...
    [model_name '/Status Warning'], ...
    'Value', '1', ...
    'Position', [520 390 610 420]);

add_block('simulink/Sources/Constant', ...
    [model_name '/Status OK'], ...
    'Value', '0', ...
    'Position', [520 450 610 480]);

%% ============================================================
%  LOW BATTERY SWITCH
%
%  low_battery = 1 -> WARNING (1)
%  low_battery = 0 -> OK (0)
% =============================================================

add_block('simulink/Signal Routing/Switch', ...
    [model_name '/Battery Status Switch'], ...
    'Threshold', '0.5', ...
    'Criteria', 'u2 >= Threshold', ...
    'Position', [670 390 790 470]);

%% ============================================================
%  HIGH TEMPERATURE SWITCH
%
%  high_temperature = 1 -> CRITICAL (2)
%  high_temperature = 0 -> battery status
% =============================================================

add_block('simulink/Signal Routing/Switch', ...
    [model_name '/Temperature Priority Switch'], ...
    'Threshold', '0.5', ...
    'Criteria', 'u2 >= Threshold', ...
    'Position', [850 180 1000 260]);

%% ============================================================
%  FINAL STATUS SCOPE
% =============================================================

add_block('simulink/Sinks/Scope', ...
    [model_name '/Health Status Scope'], ...
    'Position', [1060 195 1200 245]);

%% ============================================================
%  SIGNAL CONNECTIONS
% =============================================================

% Temperature -> temperature scope
add_line(model_name, ...
    'Temperature Input/1', ...
    'Temperature Scope/1');

% Temperature -> high-temperature comparator
add_line(model_name, ...
    'Temperature Input/1', ...
    'High Temperature Check/1');

% Altitude -> scope
add_line(model_name, ...
    'Altitude Input/1', ...
    'Altitude Scope/1');

% Velocity -> scope
add_line(model_name, ...
    'Velocity Input/1', ...
    'Velocity Scope/1');

% Battery -> scope
add_line(model_name, ...
    'Battery Input/1', ...
    'Battery Scope/1');

% Battery -> low-battery comparator
add_line(model_name, ...
    'Battery Input/1', ...
    'Low Battery Check/1');

%% ============================================================
%  LOW BATTERY STATUS LOGIC
% =============================================================

% Warning constant -> upper data input
add_line(model_name, ...
    'Status Warning/1', ...
    'Battery Status Switch/1');

% OK constant -> lower data input
add_line(model_name, ...
    'Status OK/1', ...
    'Battery Status Switch/3');

% Low battery comparator -> switch control
add_line(model_name, ...
    'Low Battery Check/1', ...
    'Battery Status Switch/2');

%% ============================================================
%  TEMPERATURE PRIORITY LOGIC
% =============================================================

% Critical constant -> upper data input
add_line(model_name, ...
    'Status Critical/1', ...
    'Temperature Priority Switch/1');

% Battery status -> lower data input
add_line(model_name, ...
    'Battery Status Switch/1', ...
    'Temperature Priority Switch/3');

% High temperature comparator -> switch control
add_line(model_name, ...
    'High Temperature Check/1', ...
    'Temperature Priority Switch/2');

%% ============================================================
%  FINAL STATUS -> SCOPE
% =============================================================

add_line(model_name, ...
    'Temperature Priority Switch/1', ...
    'Health Status Scope/1');

%% ============================================================
%  SAVE
% =============================================================

save_system(model_name, model_path);

fprintf('\n');
fprintf('============================================\n');
fprintf('ATFIDP Simulink Model Generated\n');
fprintf('============================================\n');
fprintf('Model: %s\n', model_path);
fprintf('Solver: Fixed-step discrete\n');
fprintf('Step:   0.1 s\n');
fprintf('Time:   0 -> 60 s\n');
fprintf('Health logic:\n');
fprintf('  Temperature > 80 C -> CRITICAL (2)\n');
fprintf('  Battery < 20 V      -> WARNING  (1)\n');
fprintf('  Otherwise            -> OK       (0)\n');
fprintf('============================================\n');